FROM openjdk:8-jre-alpine
RUN  apk update && apk upgrade && apk add netcat-openbsd && apk add tar
RUN  mkdir -p /usr/local/pipeline-demo

ARG JAR_FILE
COPY target/${JAR_FILE} /usr/local/pipeline-demo/pipeline-demo.jar

ENV PROFILE <spring-profile>
ENV MYSQL_HOST <your-mysql-host>
ENV MYSQL_USER <your-mysql-user>
ENV MYSQL_USER_PASSWORD <your-mysql-password>

CMD ["/bin/sh", "-c", "java -Dspring.profiles.active=${PROFILE} -jar /usr/local/pipeline-demo/pipeline-demo.jar"]
